apiVersion: v1
kind: Secret
metadata:
  name: aeropath-secrets
  namespace: aeropath
type: Opaque
stringData:
  database-url: "postgres://aeropath:secret@postgres:5432/aeropath?sslmode=disable"
  jwt-secret: "change-me-in-production-use-a-real-secret"
  redis-password: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: aeropath
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'aeropath-api'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: api-gateway
            action: keep
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: "true"
            action: keep
          - source_labels: [__address__]
            action: replace
            regex: ([^:]+)(?::\d+)?
            replacement: $1:9090
            target_label: __address__

      - job_name: 'aeropath-worker'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: worker
            action: keep
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: "true"
            action: keep
